version: "3"
services:
  reverseproxy:
      image: lynettemidy/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - udagram-backend-user
        - udagram-backend-feed     
  udagram-backend-user:
    image: lynettemidy/udagram-backend-user
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      FRONTEND_URL: "http://localhost:8100"
  udagram-backend-feed:
    image: lynettemidy/udagram-backend-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DB
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_MEDIA_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      FRONTEND_URL: $FRONTEND_URL
  udagram-frontend:
    image: lynettemidy/udagram-frontend
    ports:
      - "8100:80"